"""empty message

Revision ID: 2adf41103438
Revises: f95825ec4ce4
Create Date: 2024-05-01 00:09:13.559478

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2adf41103438'
down_revision = 'f95825ec4ce4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_characters')
    op.drop_table('favorites_planets')
    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.drop_constraint('characters_favorites_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorites_id')

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('characters_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicles_id', sa.Integer(), nullable=True))
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.create_foreign_key(None, 'vehicles', ['vehicles_id'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['characters_id'], ['id'])
        batch_op.create_foreign_key(None, 'planets', ['planets_id'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.drop_constraint('planets_favorites_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorites_id')

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_constraint('vehicles_favorites_id_fkey', type_='foreignkey')
        batch_op.drop_column('favorites_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('vehicles_favorites_id_fkey', 'favorites', ['favorites_id'], ['id'])

    with op.batch_alter_table('planets', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('planets_favorites_id_fkey', 'favorites', ['favorites_id'], ['id'])

    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.drop_column('vehicles_id')
        batch_op.drop_column('characters_id')
        batch_op.drop_column('planets_id')

    with op.batch_alter_table('characters', schema=None) as batch_op:
        batch_op.add_column(sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.create_foreign_key('characters_favorites_id_fkey', 'favorites', ['favorites_id'], ['id'])

    op.create_table('favorites_planets',
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('planet_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], name='favorites_planets_favorite_id_fkey'),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], name='favorites_planets_planet_id_fkey'),
    sa.PrimaryKeyConstraint('favorite_id', 'planet_id', name='favorites_planets_pkey')
    )
    op.create_table('favorites_characters',
    sa.Column('favorite_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], name='favorites_characters_character_id_fkey'),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], name='favorites_characters_favorite_id_fkey'),
    sa.PrimaryKeyConstraint('favorite_id', 'character_id', name='favorites_characters_pkey')
    )
    # ### end Alembic commands ###
