"""empty message

Revision ID: 4fc1c9f75431
Revises: 2adf41103438
Create Date: 2024-05-01 00:33:21.467400

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4fc1c9f75431'
down_revision = '2adf41103438'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planet_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('character_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('vehicle_id', sa.Integer(), nullable=True))
        batch_op.drop_constraint('favorites_characters_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_vehicles_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('favorites_planets_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'planets', ['planet_id'], ['id'])
        batch_op.create_foreign_key(None, 'characters', ['character_id'], ['id'])
        batch_op.create_foreign_key(None, 'vehicles', ['vehicle_id'], ['id'])
        batch_op.drop_column('vehicles_id')
        batch_op.drop_column('characters_id')
        batch_op.drop_column('planets_id')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('favorites', schema=None) as batch_op:
        batch_op.add_column(sa.Column('planets_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('characters_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('vehicles_id', sa.INTEGER(), autoincrement=False, nullable=True))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('favorites_planets_id_fkey', 'planets', ['planets_id'], ['id'])
        batch_op.create_foreign_key('favorites_vehicles_id_fkey', 'vehicles', ['vehicles_id'], ['id'])
        batch_op.create_foreign_key('favorites_characters_id_fkey', 'characters', ['characters_id'], ['id'])
        batch_op.drop_column('vehicle_id')
        batch_op.drop_column('character_id')
        batch_op.drop_column('planet_id')

    # ### end Alembic commands ###
