"""empty message

Revision ID: 676ac89cb919
Revises: d851a6338a58
Create Date: 2024-04-28 23:56:40.084853

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '676ac89cb919'
down_revision = 'd851a6338a58'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('favorites_planets',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('planet_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], ),
    sa.ForeignKeyConstraint(['planet_id'], ['planets.id'], ),
    sa.PrimaryKeyConstraint('favorite_id', 'planet_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('favorites_planets')
    # ### end Alembic commands ###
