"""empty message

Revision ID: f95825ec4ce4
Revises: 676ac89cb919
Create Date: 2024-04-30 20:46:53.619396

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f95825ec4ce4'
down_revision = '676ac89cb919'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('characters',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('hair_color', sa.String(length=40), nullable=False),
    sa.Column('eye_color', sa.String(length=40), nullable=False),
    sa.Column('skin_color', sa.String(length=50), nullable=False),
    sa.Column('gender', sa.String(length=50), nullable=False),
    sa.Column('favorites_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('favorites_characters',
    sa.Column('favorite_id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['characters.id'], ),
    sa.ForeignKeyConstraint(['favorite_id'], ['favorites.id'], ),
    sa.PrimaryKeyConstraint('favorite_id', 'character_id')
    )
    op.drop_table('people')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('people',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.Column('hair_color', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('eye_color', sa.VARCHAR(length=40), autoincrement=False, nullable=False),
    sa.Column('skin_color', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('gender', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('favorites_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['favorites_id'], ['favorites.id'], name='people_favorites_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='people_pkey')
    )
    op.drop_table('favorites_characters')
    op.drop_table('characters')
    # ### end Alembic commands ###
